version: '2'

networks:
  project2:

services:

  orderer.finalexam.com:
    container_name: orderer.finalexam.com
    image: hyperledger/fabric-orderer:x86_64-1.1.0
    environment:
      - ORDERER_GENERAL_LOGLEVEL=INFO
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/var/hyperledger/orderer/orderer.genesis.block
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
      - ORDERER_GENERAL_TLS_ENABLED=true
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: orderer
    volumes:
    - ./orderer/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
    - ./crypto-config/ordererOrganizations/finalexam.com/orderers/orderer.finalexam.com/msp:/var/hyperledger/orderer/msp
    - ./crypto-config/ordererOrganizations/finalexam.com/orderers/orderer.finalexam.com/tls/:/var/hyperledger/orderer/tls
    ports:
      - 7050:7050
    networks:
      - project2

  peer0.org1.finalexam.com:
    container_name: peer0.org1.finalexam.com
    extends:
      file:  peer.yaml
      service: peer
    environment: 
      - CORE_PEER_ID=peer0.org1.finalexam.com 
      - CORE_PEER_ADDRESS=peer0.org1.finalexam.com:7051 
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.org1.finalexam.com:7051 
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.org1.finalexam.com:7051 
      - CORE_PEER_LOCALMSPID=Org1MSP 
    volumes: 
        - ./crypto-config/peerOrganizations/org1.finalexam.com/peers/peer0.org1.finalexam.com/msp:/etc/hyperledger/fabric/msp 
        - ./crypto-config/peerOrganizations/org1.finalexam.com/peers/peer0.org1.finalexam.com/tls:/etc/hyperledger/fabric/tls 
    ports: 
      - 7051:7051 
      - 7053:7053 
    networks:
      - project2

  peer1.org1.finalexam.com:
    container_name: peer1.org1.finalexam.com
    extends:
      file:  peer.yaml
      service: peer
    environment: 
      - CORE_PEER_ID=peer1.org1.finalexam.com 
      - CORE_PEER_ADDRESS=peer1.org1.finalexam.com:7051 
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.org1.finalexam.com:7051 
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.org1.finalexam.com:7051 
      - CORE_PEER_LOCALMSPID=Org1MSP 
    volumes: 
        - ./crypto-config/peerOrganizations/org1.finalexam.com/peers/peer1.org1.finalexam.com/msp:/etc/hyperledger/fabric/msp 
        - ./crypto-config/peerOrganizations/org1.finalexam.com/peers/peer1.org1.finalexam.com/tls:/etc/hyperledger/fabric/tls 
    ports: 
      - 8051:7051 
      - 8053:7053 
    networks:
      - project2 

  peer0.org2.finalexam.com:
    container_name: peer0.org2.finalexam.com
    extends:
      file:  peer.yaml
      service: peer
    environment: 
      - CORE_PEER_ID=peer0.org2.finalexam.com 
      - CORE_PEER_ADDRESS=peer0.org2.finalexam.com:7051 
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.org2.finalexam.com:7051 
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.org2.finalexam.com:7051 
      - CORE_PEER_LOCALMSPID=Org2MSP 
    volumes: 
        - ./crypto-config/peerOrganizations/org2.finalexam.com/peers/peer0.org2.finalexam.com/msp:/etc/hyperledger/fabric/msp 
        - ./crypto-config/peerOrganizations/org2.finalexam.com/peers/peer0.org2.finalexam.com/tls:/etc/hyperledger/fabric/tls 
    ports: 
      - 9051:7051 
      - 9053:7053 
    networks:
      - project2 

  peer1.org2.finalexam.com:
    container_name: peer1.org2.finalexam.com
    extends:
      file:  peer.yaml
      service: peer
    environment: 
      - CORE_PEER_ID=peer1.org2.finalexam.com 
      - CORE_PEER_ADDRESS=peer1.org2.finalexam.com:7051 
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.org2.finalexam.com:7051 
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.org2.finalexam.com:7051 
      - CORE_PEER_LOCALMSPID=Org2MSP 
    volumes: 
        - ./crypto-config/peerOrganizations/org2.finalexam.com/peers/peer1.org2.finalexam.com/msp:/etc/hyperledger/fabric/msp 
        - ./crypto-config/peerOrganizations/org2.finalexam.com/peers/peer1.org2.finalexam.com/tls:/etc/hyperledger/fabric/tls 
    ports: 
      - 10051:7051 
      - 10053:7053 
    networks:
      - project2 

  cli:
    container_name: cli
    image: hyperledger/fabric-tools:x86_64-1.1.0
    tty: true
    stdin_open: true
    environment:
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_LOGGING_LEVEL=INFO
      - CORE_PEER_ID=cli
      - CORE_PEER_ADDRESS=peer0.org1.finalexam.com:7051
      - CORE_PEER_LOCALMSPID=Org1MSP
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org1.finalexam.com/peers/peer0.org1.finalexam.com/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org1.finalexam.com/peers/peer0.org1.finalexam.com/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org1.finalexam.com/peers/peer0.org1.finalexam.com/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org1.finalexam.com/users/Admin@org1.finalexam.com/msp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash
    volumes:
        - /var/run/:/host/var/run/
        - ./orderer/:/opt/gopath/src/github.com/hyperledger/fabric/peer/orderer
        - ./chaincode/:/opt/gopath/src/github.com/chaincode
        - ./crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
        - ./scripts:/opt/gopath/src/github.com/hyperledger/fabric/peer/scripts/
        - ./channels:/opt/gopath/src/github.com/hyperledger/fabric/peer/channel-artifacts
    depends_on:
      - orderer.finalexam.com
      - peer0.org1.finalexam.com
      - peer1.org1.finalexam.com
      - peer0.org2.finalexam.com
      - peer1.org2.finalexam.com
    networks:
      - project2 

